version: '3.7'
services:
  zookeeper:
    hostname: zookeeper
    image: confluentinc/cp-zookeeper
    environment:
     - ZOOKEEPER_CLIENT_PORT=2181
    ports:
     - "2181:2181"
    volumes:
      - C:\docker_volumes\vol1\zk-data:/var/lib/zookeeper/data
      - C:\docker_volumes\vol2\zk-txn-logs:/var/lib/zookeeper/log 
  kafka:
    hostname: kafka
    depends_on: 
      - "zookeeper"
    image: confluentinc/cp-kafka
    environment:
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
     - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
     - "9092:9092"
    volumes:
      - C:\docker_volumes\vol3\kafka-data:/var/lib/kafka/data
  topicCreator:
    image: confluentinc/cp-kafka
    env_file: 
      - .env
    depends_on:
      - zookeeper
      - kafka
    command: |
      bash -c 'echo Waiting for Kafka to be ready... && \
      cub kafka-ready -b kafka:9092 1 200 && \
      kafka-topics --create --topic ${KAFKA_TOPIC_NAME} --partitions 1 --replication-factor 1 --if-not-exists --zookeeper zookeeper:2181 && \
      sleep 1000'
  schema-registry:
    image: confluentinc/cp-schema-registry
    hostname: schema-registry
    ports:
    - "38081:38081"
    depends_on:
    - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:38081
      SCHEMA_REGISTRY_DEBUG: "true"
  kafka-rest:
    image: confluentinc/cp-kafka-rest
    hostname: kafka-rest
    ports:
    - "38082:38082"
    depends_on:
      - schema-registry
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_HOST_NAME: kafka-rest
      KAFKA_REST_LISTENERS: http://kafka-rest:38082
      KAFKA_REST_SCHEMA_REGISTRY_URL: schema-registry:38081
  control-center:
    image: confluentinc/cp-enterprise-control-center:5.0.0
    hostname: control-center
    container_name: control-center
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka:9092
      CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021

